server:
  port: 8001 #端口
  servlet:
    context-path: /customer
provider:
  url: http://localhost:8002/provider
spring:
  application:
    name: customer #应用名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka


