server:
  port: 8002 #端口
  servlet:
    context-path: /customer
provider:
  url: http://localhost:8001/provider
spring:
  application:
    name: customer-demo #应用名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
