server:
  port: 8006
  servlet:
    context-path: /feign-hystrix
spring:
  application:
    name: feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
feign:
  hystrix:
    enabled: true