server:
  port: 8001 #端口
  servlet:
    context-path: /provider

spring:
  application:
    name: provider-demo #应用名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka # eureka服务端注册地址




